apimServiceName: apim-apiops-prd
namedValues:
  - name: plainvalue
    properties:
      displayName: plainvalue
      value: "https://www.PROD.search2.com"
  - name: secret
    properties:
      displayName: secret
      value: "PRODsecret"
loggers:
diagnostics:
backends:
apis:
